include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Relax public_member_api_docs until Sprint 003 when production code begins.
    # PoC code (lib/poc/) does not need full dartdoc coverage.
    public_member_api_docs: false
